name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: python -m unittest discover tests

    Publish:
        needs: Test
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build artifact
          run: |
            # Replace these commands with the commands you use to build your application
            echo "Building application..."
            mkdir app-artifact
            cp -r ./app ./app-artifact/app
            cp ./requirements.txt ./app-artifact
            cp ./run.py ./app-artifact

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: app-artifact
            path: ./app-artifact