name: Deploy
on:
    workflow_run:
        workflows: ["Build"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Download artifact from another workflow
          run: |
                # Get the ID of the last successful run of the workflow
                run_id=$(curl --silent --show-error -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs?status=success&event=push" \
                    | jq -r '.workflow_runs[0].id')

                # Get the download URL of the artifact
                download_url=$(curl --silent --show-error -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/artifacts" \
                    | jq -r '.artifacts[] | select(.name=="app-artifact") | .archive_download_url')

                # Download the artifact
                curl -L -o app-artifact.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $download_url

                # Extract the artifact
                unzip app-artifact.zip -d ./app-artifact

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy to Azure App Service
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'theweatherapp-app'
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
            package: ./app-artifact