name: Infrastructure

on:
    workflow_dispatch:

env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init
          working-directory: infrastructure

        - name: Terraform Validate
          run: terraform validate
          working-directory: infrastructure

        - name: Terraform Plan
          run: terraform plan
          working-directory: infrastructure

        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: infrastructure
